name: CI/CD

permissions: read-all

on:
  push:
    branches:
      - main
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - .gitignore
      - README.md
      - LICENCE

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      publish: true
